name: Angular CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write # Bắt buộc để ghi vào gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href /core-computer/ --deploy-url /core-computer/

      - name: List dist
        run: ls -R dist/core-computer

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/core-computer/browser
          clean: true
